baseURL = ""
languageCode = "es-ES"
title = "DevsChile.create('Persa')"
theme = "smol"

[params]
  subtitle = "VENDE y COMPRA dentro de la comunidad."
  dateFmt = "02.01.2006"
  truncated = 50

# Header
[menu]
  [[menu.main]]
    identifier = "cachureos"
    name = "Cachureos"
    url = "/cachureos/"
    weight = 1 

  [[menu.main]]
    identifier = "categories"
    name = "Categorías"
    url = "/categories/"
    weight = 2 

  [[menu.main]]
    identifier = "tags"
    name = "Etiquetas"
    url = "/tags/"
    weight = 3

# Footer
  [[menu.footer]]
    name = "Sitio"
    url = "https://devschile.cl/"
    weight = 1 

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/devschile/"
    weight = 2 

  [[menu.footer]]
    name = "Twitter"
    url = "https://www.twitter.com/devschile"
    weight = 3 
